name: PR's to Main should come only from devel

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          echo "PR from: ${{ github.head_ref }}"
          if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" != "devel" ]; then
            echo "❌ Pull requests to main must come from devel branch only."
            exit 1
          fi